# Generated by Django 3.0.5 on 2021-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeldb', '0006_auto_20211120_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portproject',
            name='files',
            field=models.FileField(blank=True, upload_to='static/'),
        ),
    ]
