# Generated by Django 3.0.5 on 2021-11-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeldb', '0010_auto_20211128_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
