# Generated by Django 3.0.5 on 2021-11-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeldb', '0011_auto_20211129_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, upload_to='messages/'),
        ),
    ]
